language: java

sudo: false

jdk:
  - openjdk8
  -
env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"

addons:

  sonarcloud:

    organization: "gwas-ebi"

    token:

      secure: "qVzaWu5Z+YM5KUZjqqzyV5Q7yV3lPN/DILhCobftM44eEujF9BK2SJIXiorekufirs87deU9l71c29L4sSrHl0InJXZ+v69a8qdJSRBXpNFwW4chQEiDNDm0kdnQshMymofAQdM55Uwsqxud2DGYPRs5Yfa+5vC95/fo2+RfRYOQ5TikyQKuu8z2TvTFel62yNnUrKEKHkK5TMTu6+tjdwaYMeSrV3jHScCAMINx4SyIxsabUYB3PMqz6kIBXXj0csPLQ6JzGRej7gxBxtR+0VLNcTomgDmgmRi7T/0gd2mBQgF8iRTkKc3syIoMCk/2ueYnR2gpmZF0ubfUb8TE9Fi5YpZWnDEYUwfS3/ru1QtTp05ZbzPo/D3wtp+1DYeJ69hoUuV6zYSoIvn+aQCaahHUjed+ulmcek+/XAHKekfr3+IqJ/IPSyizIoeGbRyJZVkehaH0DvxNkH6ceoc4MlHmDbPNew3pApo4N+YmuKC8qhgnhVUQrWJLZz7F2xmBD56TvQXf+92oYu0pTnEMuiRq2j/n0sfXSpvvCZDVySkoYfxxcpO/kly9HJsnuPxCNEB2axwsZpOmqU0KGitYmgkjury+jFGFiFOCX6Ogjk99T1hMSFHzXMmUhCn97qzGfG7nexrhCb5yNHrZlB94jar/6t7MLXBX+C6LNFjT3+0="



script:

  - mvn sonar:sonar -Dsonar.projectKey=uk.ac.ebi.spot.gwasdepo:gwasdepo-deposition-service -Dspring.profiles.active=test -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true