server:
  port: 8080
  servlet:
    context-path: /gwas/deposition/api

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: rabbitmq.rabbitmq.svc.cluster.local
    port: 5672
    username: ebigwasuser
  data:
    mongodb:
      #uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039
      uri: mongodb-hx-gwasdepopro-001.ebi.ac.uk:27017,mongodb-hl-gwasdepopro-002.ebi.ac.uk:27017/admin?replicaSet=gwasdepoprors080
    solr:
      host: http://solr-svc.solr:8983/solr/
  mail:
    host: hh-smtp.ebi.ac.uk
    port: 25
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: false
          sendpartial: true
          starttls:
            enable: true

audit:
  enabled: true

quartz:
  scheduler:
    dbName: gwasdepo

gwas-deposition:
  auth:
    enabled: true
    unauthenticated-endpoints: /gwas/deposition/api/v1/publications
  db: gwasdepo
  solr:
    enabled: true
  email-config:
    errors:
      active: true

email:
  enabled: true

gwas-template-service:
  enabled: true

gwas-catalog-service:
  enabled: false

solr:
  enable:
    alias: true

rabbitmq:
  queue-name: study_change
  exchange-name: study_change_exchange
  routing-key: study-ingest