server:
  port: 8080
  servlet:
    context-path: /gwas/deposition/api

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      #uri: mongo-0.mongo.gwas-dev.svc.cluster.local,mongo-1.mongo.gwas-dev.svc.cluster.local,mongo-2.mongo.gwas-dev.svc.cluster.local:27017
      uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039
      #uri: mongodb-hx-gwasdepopro-001:27017,mongodb-hl-gwasdepopro-002:27017/admin?replicaSet=gwasdepoprors080
    solr:
      host: http://solr-svc.gwas-dev.svc.cluster.local:8983/solr/
    rabbitmq:
      host: rabbitmq-dev
      port: 5672
  mail:
    host: hh-smtp.ebi.ac.uk
    port: 25
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: false
          sendpartial: true
          starttls:
            enable: true

audit:
  enabled: true
  url: http://gwas-audit-service-dev:8080

quartz:
  scheduler:
    #dbName: deposition-backend-sandbox
    dbName: gwasdepo

gwas-deposition:
  auth:
    enabled: true
    unauthenticated-endpoints: /gwas/deposition/api/v1/publications
  #db: deposition-backend-sandbox
  db: gwasdepo
  proxy-prefix: /gwas/deposition/api
  solr:
    enabled: true
  email-config:
    base-url: http://193.62.54.159/gwas/deposition/submission/

email:
  enabled: true

gwas-sumstats-service:
  url: http://gwas-ss-service-dev:8000

gwas-template-service:
  enabled: true
  url: http://gwas-template-service-dev:8080




gwas-catalog-service:
  enabled: false

solr:
  enable:
    alias: true
