server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039
    solr:
      host: http://localhost:8983/solr

gwas-deposition:
  db: gwasdepo
  solr:
    enabled: false
  auth:
    curators:
      auth-mechanism: EMAIL_WHITELISTING

gwas-sumstats-service:
  callback-schedule:
    enabled: false

quartz:
  scheduler:
    dbName: gwasdepo
