server:
  port: 8080

spring:
  data:
    mongodb:
      uri: snoopy.ebi.ac.uk:27017
    solr:
      host: http://localhost:8983/solr

gwas-deposition:
  db: gwas-deposition-dev
  solr:
    enabled: false
  auth:
    curators:
      auth-mechanism: EMAIL_WHITELISTING

gwas-sumstats-service:
  callback-schedule:
    enabled: true

quartz:
  scheduler:
    dbName: gwas-deposition-dev

management:
  metrics:
    export:
      newrelic:
        api-key: "eu01xxb51cef090fc9b5942caa79818605cfNRAL"
        account-id: "3065202"