
#===============COMPULSORY PROGRAM ARGUMENTS=====#
mongo-server:
auth-enable:
solr-server:
#===============COMPULSORY PROGRAM ARGUMENTS=====#

server:
  port: 8082



spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
  data:
    mongodb:
      uri: ${mongo-server}
    solr:
      host: ${solr-server}
    datasource:
      url: jdbc:mysql://ensembldb.ensembl.org:3306/homo_sapiens_variation_107_38
      username: anonymous
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver


gwas-deposition:
  db: gwasdepo
  solr:
    enabled: true
  auth:
    curators:
      auth-mechanism: EMAIL_WHITELISTING

gwas-sumstats-service:
  url: http://localhost:8000
  callback-schedule:
    enabled: true


gwas-template-service:
  enabled: true
  url: http://localhost:8083

quartz:
  scheduler:
    active: false
    dbName: gwasdepo
